version: 2.1

executors:
  jdk17:
    docker:
      - image: cimg/openjdk:17.0
  xcode15:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1

orbs:
  android: circleci/android@2.5.0

jobs:
  detekt:
    executor: jdk17
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Run Detekt on commonMain
          command: ./gradlew detektCommonMain
      - android/save-gradle-cache
      - run:
          name: Collect Detekt HTML reports
          command: mkdir -p artifacts/detekt && mv build/reports/detekt/*.html artifacts/detekt/
      - store_artifacts:
          path: artifacts/detekt
          destination: detekt
  validate-binary-compatibility:
    executor: xcode15
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Validate binary compatibility
          command: ./gradlew apiCheck
      - android/save-gradle-cache


workflows:
  build-test-deploy:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - detekt
      - validate-binary-compatibility
