version: 2.1

aliases:
  android-executor: &android-executor
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2024.04.1
    environment:
      JVM_OPTS: -Xmx6g
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

orbs:
  android: circleci/android@2.5.0

commands:
  install-sdkman:
    description: Install SDKMAN
    steps:
      - run:
          name: Installing SDKMAN
          command: |
            if curl -s "https://get.sdkman.io?rcupdate=false" | bash; then
              echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
              source $BASH_ENV
            else
              echo "Error installing SDKMAN, continuing with default Java" >&2
            fi
      - run:
          name: Setup Java environment
          command: |
            if ! sdk env install; then
              echo "Error installing Java SDK through SDKMAN, continuing with default Java" >&2
            fi

jobs:
  detekt:
    <<: *android-executor
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - install-sdkman
      - android/restore-gradle-cache
      - run:
          name: Run Detekt on commonMain
          command: ./gradlew detektCommonMain
      - android/save-gradle-cache
      - run:
          name: Collect Detekt HTML reports
          command: mv build/reports/detekt/*.html artifacts/detekt/
      - store_artifacts:
          path: artifacts/detekt
          destination: detekt

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-test-deploy:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - detekt
