version: 2.1

orbs:
  android: circleci/android@2.5.0
  revenuecat: revenuecat/sdks-common-config@3.0.0

commands:
  install-android-sdk-on-macos:
    description: Install the Android SDK on macOS
    steps:
      - run:
          name: Install Android SDK commandline tools
          command: brew install --cask android-commandlinetools
      - run:
          name: Set Android SDK environment variables
          command: |
            echo 'export ANDROID_HOME="$HOMEBREW_PREFIX/share/android-commandlinetools"' >> "$BASH_ENV"
            echo 'export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"' >> "$BASH_ENV"
      - android/accept-licenses
      - run:
          name: Install Android SDK platform tools
          command: sdkmanager "platform-tools"

parameters:
  action:
    type: enum
    enum: [ build, upgrade-hybrid-common, bump ]
    default: build
  automatic:
    type: boolean
    default: false
  version:
    type: string
    default: ''

executors:
  ruby3:
    docker:
      - image: cimg/ruby:3.3.0
  xcode15:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1
    environment:
      # Avoid waiting for Homebrew to auto update existing packages, as everything we care about is
      # freshly installed.
      HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  update-purchases-hybrid-common-version:
    description: "Opens a PR updating the purchases-hybrid-common dependency to the latest version."
    executor: ruby3
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - revenuecat/trust-github-key
      - revenuecat/setup-git-credentials
      - run:
          name: Update purchases-hybrid-common to << pipeline.parameters.version >>
          command: |
            bundle exec fastlane update_hybrid_common \
            version:<< pipeline.parameters.version >> \
            open_pr:true \
            automatic_release:<< pipeline.parameters.automatic >>

  publish:
    description: "Publishes the SDK, either a SNAPSHOT or release version."
    executor: xcode15
    parameters:
      snapshot:
        description: Whether to publish a SNAPSHOT version. Will publish a final release if set to false.
        type: boolean
    steps:
      - checkout
      - install-android-sdk-on-macos
      - android/restore-gradle-cache
      - android/restore-build-cache
      - when:
          condition: << parameters.snapshot >>
          steps:
            - run:
                name: "Publish snapshot to Sonatype's snapshots repository"
                command: bundle exec fastlane publish_if_snapshot
      - unless:
          condition: << parameters.snapshot >>
          steps:
            - run:
                name: "Publish release to Maven Central"
                command: bundle exec fastlane publish_if_release
      - android/save-gradle-cache
      - android/save-build-cache

  create-github-release:
    description: "Creates a GitHub release for the current version"
    executor: ruby3
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - revenuecat/trust-github-key
      - run:
          name: "Create a GitHub release for the current version"
          command: bundle exec fastlane github_release_current_version

workflows:
  danger:
    jobs:
      - revenuecat/danger:
          context: danger-bot

  on-action-upgrade-hybrid-common:
    when:
      equal: [ upgrade-hybrid-common, << pipeline.parameters.action >> ]
    jobs:
      - update-purchases-hybrid-common-version:
          context:
            - git-user-ops
            - github-bot-public

  on-main-branch:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - publish:
          snapshot: true
          context: maven-central-publishing

  # The release train starts with the release-train workflow, which is automatically 
  # triggered every week, but can also be triggered manually by passing the "action" 
  # parameter with a value of "bump".
  # This workflow will create a new release branch and open a PR for it. This new 
  # release branch triggers the next workflow: on-release-branch.
  release-train:
    when:
      or:
        - and:
            - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
            - equal: [ "release-train", << pipeline.schedule.name >> ]
        - equal: [ bump, << pipeline.parameters.action >> ]
    jobs:
      - revenuecat/automatic-bump

  # The second stage of the release train starts a hold job, which is a job that
  # needs to be manually approved on the CircleCI web app. This ensures there's 
  # always a human in the loop. After the hold job is approved, the current release
  # branch is tagged with the version number. This new release tag triggers the next
  # workflow: on-release-tag.
  on-release-branch:
    when:
      and:
        - matches: { pattern: "^release/.+$", value: << pipeline.git.branch >> }
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - hold:
          type: approval
      - revenuecat/tag-current-branch:
          requires:
            - hold

  # The third and last stage of the release train actually publishes the release
  # to Maven Central and creates a GitHub release for it. The release train has
  # now completed its journey.
  on-release-tag:
    when:
      and:
        - matches: { pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(?!.*-SNAPSHOT).*$", value: << pipeline.git.tag >> }
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - publish:
          snapshot: false
          context: maven-central-publishing
      - create-github-release:
          context: github-bot-public
