[versions]
agp = "8.2.2"
android-compileSdk = "34"
android-minSdk = "21"
android-targetSdk = "34"
compose = "1.6.2"
java = "1.8"
kotlin = "1.9.22"
revenuecat-android = "7.6.0"
revenuecat-ios = "4.37.0"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
arrow-core = { module = "io.arrow-kt:arrow-core", version = "1.2.1" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.5.0" }
revenuecat-android = { module = "com.revenuecat.purchases:purchases", version.ref = "revenuecat-android"}

[plugins]
adamko-dokkatoo-html = { id = "dev.adamko.dokkatoo-html", version = "2.1.0" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.5" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
gradleup-nmcp = { id = "com.gradleup.nmcp", version = "0.0.4" }
jetbrains-compose = { id = "org.jetbrains.compose", version = "1.5.12" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.27.0" }
