[versions]
agp = "8.2.2"
kotlin = "1.9.22"
revenuecat-android = "7.5.2"
revenuecat-ios = "4.36.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
revenuecat-android = { module = "com.revenuecat.purchases:purchases", version.ref = "revenuecat-android"}

[plugins]
adamko-dokkatoo-html = { id = "dev.adamko.dokkatoo-html", version = "2.1.0" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.5" }
android-library = { id = "com.android.library", version.ref = "agp" }
gradleup-nmcp = { id = "com.gradleup.nmcp", version = "0.0.4" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.27.0" }
