name: Renovate

on:
  schedule:
    - cron: '37 1 * * *'
    
jobs:

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Renovate
        uses: renovatebot/github-action@v40.1.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
